### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by nanaminato** [PGZXB/PGBigNumber#1]
I meet you at the www.zhihu.com when i would like to read the source code of how BigInteger toString() works,I am very happy that we are doing the similar thing.Without knowing whether your project is finidhed,but my project has someStage sexual progress。 My project's location is at https://github.com/Basicconstruction/BigIntegerUseVector/tree/bigger_items
。
If possibly,we could have more communication in this field in leisure time.

**Comment by PGZXB** [comment]
Thanks for your affirmation. Because of my busy campus-life the project is paused. Last commit, I finished the parser which can parse infix-expression-string to AST and eval it. I hope that the project can help me finish my next project -- a programming language.
